name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: mac
            sha_cmd: shasum -a 256
          - os: ubuntu-latest
            platform: linux
            sha_cmd: sha256sum

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Compress binary
        run: |
          cd bin
          tar -czf commute-when-${{ matrix.platform }}.tar.gz commute-when
          ${{ matrix.sha_cmd }} commute-when-${{ matrix.platform }}.tar.gz > commute-when-${{ matrix.platform }}.tar.gz.sha256

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/commute-when-${{ matrix.platform }}.tar.gz
            bin/commute-when-${{ matrix.platform }}.tar.gz.sha256
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
